provider: dimensiondata
connection:
    key: jazz
    secret: hands!
    region: dd-au
maps:
    list_instances:
        created_at: "deployedTime"
        memory_mb: "memoryMb"
        os_platform: "OS_type" 