#!/usr/bin/python
"""
List instances available in configured cloud.

Edit config.yaml to configure driver and connection settings.
"""
import json
import logging
import traceback
import sys
import rightscale

logging.info("Listing instances with parameters : %s", str(sys.argv))

CONFIG = rightscale.get_configuration()


def _to_instance(libcloud_instance, loc):
    rightscale_instance = {
        'id': libcloud_instance.id,
        'name': libcloud_instance.name,
        'state': 'running',
        'image_id': libcloud_instance.image.id
                    if libcloud_instance.image is not None else None,
        'datacenter_id': loc.id,
        'instance_type_id': libcloud_instance.size.id
                            if libcloud_instance.size is not None else None
    }
    return rightscale.map(CONFIG, 'list_instances',
                          rightscale_instance, libcloud_instance.extra)

try:
    DRIVER = rightscale.get_connection(CONFIG)
    INSTANCES = []
    LOCATIONS = DRIVER.list_locations()
    for location in LOCATIONS:
        INSTANCES.extend([_to_instance(i, location)
                          for i in DRIVER.list_nodes(ex_location=location)])

    print(json.dumps(INSTANCES))
    exit(0)

except Exception as e:
    logging.error(traceback.format_exc())
