#!/usr/bin/python
import json
import logging
import traceback
import sys
from rightscale import get_connection


logging.info("Listing instances types with parameters : %s", str(sys.argv))

def _to_instance_type(size):
    return {
        'id': size.id,
        'name': size.name,
        'description': size.name,
        'cpu_count': 1,
        'cpu_speed': 1000,
        'memory': 500,
        'local_disk_size': 500
    }

try:
    driver = get_connection()
    instances = [_to_instance_type(i) for i in driver.list_sizes()]

    print(json.dumps(instances))
    exit(0)

except Exception as e:
    logging.error(traceback.format_exc())
