#!/usr/bin/python
"""
List images available in configured cloud.

Edit config.yaml to configure driver and connection settings.
"""
import json
import logging
import traceback
import sys
from rightscale import get_connection

logging.info("Listing images with parameters : %s", str(sys.argv))


def _to_image(image):
    return {
        'id': image.id,
        'name': image.name,
        'description': image.name
    }

try:
    DRIVER = get_connection()
    IMAGES = [_to_image(i) for i in DRIVER.list_images()]

    print(json.dumps(IMAGES))
    exit(0)

except Exception as e:
    logging.error(traceback.format_exc())
