#!/usr/bin/python
import json
from rightscale import get_connection


def _to_location(loc):
    return {
        'id': loc.id,
        'name': loc.name
    }

driver = get_connection()
locations = [_to_location(loc) for loc in driver.list_locations()]

print(json.dumps(locations))
