#!/usr/bin/python
"""
List datacenters available in configured cloud.

Edit config.yaml to configure driver and connection settings.
"""
import json
import traceback
import logging
from rightscale import get_connection


def _to_location(loc):
    return {
        'id': loc.id,
        'name': loc.name
    }

try:
    DRIVER = get_connection()
    LOCATIONS = [_to_location(loc) for loc in DRIVER.list_locations()]
    print(json.dumps(LOCATIONS))
    exit(0)

except Exception as exception:
    logging.error(traceback.format_exc())
