#!/usr/bin/python
import json
from rightscale import get_connection


def _to_image(image):
    return {
        'id': image.id,
        'name': image.name,
        'description': image.name
    }

driver = get_connection()
images = [_to_image(i) for i in driver.list_images()]

print(json.dumps(images))
