#!/usr/bin/python
import json
import logging
import traceback
import sys
from rightscale import get_connection

logging.info("Listing images with parameters : %s", str(sys.argv))


def _to_image(image):
    return {
        'id': image.id,
        'name': image.name,
        'description': image.name
    }

try:
    driver = get_connection()
    images = [_to_image(i) for i in driver.list_images()]

    print(json.dumps(images))
    exit(0)

except Exception as e:
    logging.error(traceback.format_exc())
